//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDoctor.Models
{
    using System;
    using System.Collections.Generic;


    public partial class BacSi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacSi()
        {
            this.LichKhams = new HashSet<LichKham>();
        }
    
        public int idBacSi { get; set; }
        public string passbs { get; set; }
        public Nullable<int> idHocVi { get; set; }
      
        public string tenbs { get; set; }
        public string urlanh { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string motabs { get; set; }
        public Nullable<bool> quyen { get; set; }
    
        public virtual HocVi HocVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichKham> LichKhams { get; set; }
    }
}
