//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietThanNhan
    {
        public int idctThanNhan { get; set; }
        public string sdtThanNhan { get; set; }
        public Nullable<int> idkhachHang { get; set; }
        public string qHeVoiBenhNhan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual ThanNhan ThanNhan { get; set; }
    }
}
