//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatLich()
        {
            this.ChiTietThuocs = new HashSet<ChiTietThuoc>();
            this.KetQuaKhams = new HashSet<KetQuaKham>();
        }
    
        public int iddl { get; set; }
        public Nullable<int> idbs { get; set; }
        public Nullable<int> idkh { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public string trieuchung { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThuoc> ChiTietThuocs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQuaKham> KetQuaKhams { get; set; }
    }
}
