//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaKham
    {
        public int idkq { get; set; }
        public Nullable<int> iddl { get; set; }
        public string ketqua { get; set; }
        public string hdthuoc { get; set; }
        public Nullable<int> tienkham { get; set; }
    
        public virtual DatLich DatLich { get; set; }
    }
}
