//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichKham()
        {
            this.KetQuaKhams = new HashSet<KetQuaKham>();
        }
    
        public int idDatLich { get; set; }
        public Nullable<int> idBacSi { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public string hoten { get; set; }
        public Nullable<int> tuoi { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public string trieuchung { get; set; }
        public Nullable<bool> tinhTrang { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQuaKham> KetQuaKhams { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
