//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDoctor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDoctorEntities1 : DbContext
    {
        public myDoctorEntities1()
            : base("name=myDoctorEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BacSi> BacSis { get; set; }
        public virtual DbSet<benhAn> benhAns { get; set; }
        public virtual DbSet<chitietThanNhan> chitietThanNhans { get; set; }
        public virtual DbSet<ChiTietThuoc> ChiTietThuocs { get; set; }
        public virtual DbSet<HocVi> HocVis { get; set; }
        public virtual DbSet<KetQuaKham> KetQuaKhams { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LichKham> LichKhams { get; set; }
        public virtual DbSet<LichKhamNhap> LichKhamNhaps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThanNhan> ThanNhans { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
    }
}
