//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanNhan
    {
        public string sdtThanNhan { get; set; }
        public string tenThanNhan { get; set; }
        public string emailThanNhan { get; set; }
        public string passtn { get; set; }
        public Nullable<int> idkh { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
